### ISSUE TITLE
很喜欢您的博客主题

### ISSUE THREAD

**Issue by leon-zym** [elizen/elizen-blog#2]
博客主题好舒服啊，看您是基于 Ivy 做了很多自己的修改。请问有想法把主题单独拎出来建一个项目吗？

**Comment by elizen** [comment]
实话实说，我不会...现在乱七八糟改的东西，不是四处抄来的，就是朋友手把手教的，至于怎么把主题单拎出来，确实不知道怎么搞。

**Comment by leon-zym** [comment]
> 实话实说，我不会...现在乱七八糟改的东西，不是四处抄来的，就是朋友手把手教的，至于怎么把主题单拎出来，确实不知道怎么搞。

谢谢回复，没关系的。我也很喜欢您博客里的文字 😀
